name: 'Validate JSON data inside YAML files'
description: 'Github Action detects and validates JSON data inside the YAML files.'
author: 'Dung Pham'

inputs:
  folder_or_file:
    description: 'File(s) or Directory, separate by space if multiple files or folder are specified'
    required: false
  format:
    description: 'Format for parsing output [parsable,standard,colored,github,auto]'
    required: false
    default: "parsable"
  strict:
    description: 'Return non-zero exit code on warnings as well as errors'
    required: false
    default: "false"
  no_warnings:
    description: 'Output only error level problems'
    required: false
    default: "false"

outputs:
  result:
    description: 'The linting result'
  passed:
    description: 'Number of files passed validation'
  failed:
    description: 'Number of files failed validation'
  empty:
    description: 'Number of empty files'
  skipped:
    description: 'Number of skipped files'

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
      with:
        python-version: '3.12.0-rc.3'
    - id: lintjson-data
      run: |
        if [[ -d "/__w/_actions" ]]; then
          # This is a self-hosted container runner
          python ${GITHUB_ACTION_PATH}/main.py
        else
          # This is a vm runner
          python ${{ github.action_path }}/main.py
        fi
      shell: bash
      env:
        INPUT_FILE_OR_DIR: ${{ inputs.folder_or_file }}
        INPUT_FORMAT: ${{ inputs.format }}
        INPUT_STRICT: ${{ inputs.strict }}
        INPUT_NO_WARNINGS: ${{ inputs.no_warnings }}

branding:
  color: blue
  icon: check-square